import express, { Request, Response, Router, NextFunction } from "express";
import mongoose from "mongoose";
import {Post , validatePost} from "../models/post.js";
import bcrypt from "bcrypt";
import { AppError } from "../utils/errors.js";
import _ from "lodash";
import Joi from "joi";
import password_validator from "../utils/password_validator.js";
import jsonwebtoken from "jsonwebtoken";
import env from "../utils/env.js";
import csurf from "csurf";
import { validateLoginUser } from "../models/user.js";
